# Generated by Django 3.0.7 on 2020-06-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип сделки',
                'verbose_name_plural': 'Тип сделки',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField(default=1, verbose_name='Количество комнат')),
                ('apartment_area', models.IntegerField(help_text='Укажите без знака квадрата.', verbose_name='Площадь квартиры')),
                ('house_floor', models.IntegerField(help_text='Укажите этажность дома', verbose_name='Этажи дома')),
                ('apartment_floor', models.IntegerField(verbose_name='На каком этаже квартира')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('price_sm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за квадратный метр')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.DealType', verbose_name='Тип сделки')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.District')),
            ],
            options={
                'verbose_name': 'Обявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
