# Generated by Django 3.0.7 on 2020-06-28 10:58

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200628_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Контактный номер телефона', max_length=31),
        ),
        migrations.AlterField(
            model_name='ads',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.District', verbose_name='Район'),
        ),
    ]
